server:
  port: 8081
eureka:
  instance:
    #需要导入spring-cloud-commons，cloud2.x迁移入spring-cloud-commons
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


spring:
  application:
    name: ldm-service-code
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ldmcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
