server:
  port: 8088
eureka:
  instance:
    #需要导入spring-cloud-commons，cloud2.x迁移入spring-cloud-commons
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


spring:
  application:
    name: ldm-service-user
  datasource:
    username: dev
    password: wdphdev2018
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.53.156.240:3306/account
